- lib/actions/adapterActions.js
When opening adapter, it occasionally fails with a timeout error. If an adapter is already open, it should close that before opening. Here there was a bug, where it continued to open the adapter before the old one had been properly closed.
Also the SerialPort.open/close procedure that happens right before opening seems to cause problems for pc-ble-driver-js. There are occasional timeout errors when opening adapter. Adding a short delay before opening, so that the port/devkit has some time to clean up.
> Fix timeout errors when opening adapter

- lib/actions/deviceDetailsActions.js
- lib/components/ConnectedDevice.jsx
- lib/components/deviceDetails.jsx
- lib/reducers/adapterReducer.js
- lib/utils/definitions.js
- lib/utils/uuid_definitions.js
We now refer to UUID constants instead of looking up the UUIDs by name. The lookup by name did also search among custom UUIDs, which was problematic. The user could have specified e.g. a custom Device Name or Secure DFU UUID, which would cause the device name to not appear, or the DFU button to not be displayed.
> Fix issue with custom UUIDs interfering with normal behavior

- README.md
- package.json
Updating the name according to latest policy:
- Uppercase all words in Bluetooth Low Energy.
- Use Bluetooth® only for the first occurrence in the body text.
> Use correct Bluetooth Low Energy name

- lib/reducers/adapterReducer.js
When a devkit/dongle was unplugged while being open, an error would pop up saying: "Error when calling 'reduceApp': Cannot read property 'clear' of undefined".
This happened because the reducer tried to update the state for an already removed adapter. Now checking if the adapter exists before updating state.
> Fix cryptic error when unplugging device

- lib/actions/adapterActions.js
The AdapterFactory checks for new adapters every 2 seconds. If something fails in this routine, the same error may be emitted multiple times. Showing an error dialog in these cases will make the completely app unusable, so logging the error instead. It will show up in the log viewer and in the log file.
> Make errors from AdapterFactory less intrusive

- lib/actions/adapterActions.js
When opening an adapter with pc-ble-driver-js, it is possible to specify an `eventInterval` option, which is how often BLE events should be sent up from pc-ble-driver to pc-ble-driver-js. This has been set to 10 ms to avoid flooding the UI with events, which could make it unresponsive.
However, many changes has been made to nRF Connect since the event interval mechanism was introduced, and recent tests indicate that `eventInterval: 0` (which disables the event inverval) does not cause problems for the UI.
The main motivation for disabling the event interval is to avoid slowing down the DFU. The DFU procedure waits for events when performing write operations, so we want these events to arrive as fast as possible.
> Change BLE driver event interval from 10 ms to 0

- lib/containers/ServerSetup.jsx
In #72, a `deviceInfo` property was added to `CentralDevice`. This component is used by both `DeviceDetails` and `ServerSetup`, but the device info was only specified by `DeviceDetails`. Adding it to `ServerSetup` as well.
> Fix issue with server setup not opening

- index.jsx
- lib/actions/adapterActions.js
- lib/api/nrfjprog.js
- lib/reducers/__tests__/dfuReducer-test.js
- lib/reducers/__tests__/discoveryReducer-test.js
- lib/reducers/__tests__/serverSetupReducer-test.js
- lib/reducers/adapterReducer.js
This replaces #74, which is now conflicting with master. Using open/close from pc-nrfjprog-js so that getting the probe info does not slow down opening the serial port.
Note: I took the liberty to remove the connectivity firmware's transport type from the log output as it only said "transportType: 1", which is not very informative. Let me know if we still need to log this. In that case, I think we should show what the "1" actually means.
> Log J-Link firmware string when selecting serial port

- lib/actions/adapterActions.js
- lib/actions/serverSetupActions.js
The CentralDevice and ServerSetup components require a `deviceInfo` prop. This device info needs to be loaded from nrfjprog and added to state before opening the adapter. If not, the CentralDevice and ServerSetup will fail to render.
Added a short-term fix for this in `resetAndApplyServer` now, but I think this needs to be refactored. We should not have to remember to dispatch LOCAL_DEVICE_INFO_LOADED before opening the adapter. This is easy to forget, and will lead to bugs like this. If it is required for opening the adapter, then it should probably be handled by `AdapterActions.openAdapter` instead.
>  Fix issue when resetting and applying server setup

- README.md
- lib/components/__tests__/DfuEditor-test.jsx
- lib/components/__tests__/ServiceItem-test.jsx
- package.json
Also now using semver caret in dependency, so that we get new patch or minor versions automatically. Fixed some previously undetected linting errors in tests.
>  Update devdep version to fix jsx linting issue

- lib/components/CentralDevice.jsx
- package.json
Many menu items were unintentionally shown in the server setup view, and clicking the items did not work. This is a bug that was introduced in the standalone application -> nRF Connect app rewrite. Fixing this.
Before fix:
After fix:
> Hide menu items in the server setup view

- lib/reducers/discoveryReducer.js
This is my proposal to address issue #95, whereas in the old solution neither the direction nor the level of merge was sufficient. This solution however would not reflect if some field gets deleted from the advertisement.
> Fix ADV packet update by merging existing and new

- lib/actions/adapterActions.js
- lib/reducers/deviceDetailsReducer.js
Add better handling of attribute updates for the case when updates are received for multiple attributes within the same throttling interval. This is handled by batching together updates instead of masking them out.
> Improve attribute throttling mechanism

- lib/components/CentralDevice.jsx
- lib/containers/DiscoveredDevices.jsx
This PR fixes lost Alt+A shortcut by moving the binding to the correct lifecycle method.
Alt+C is also moved for consistency, there's no need to repeat the binding for every render.
> Fix binding of keyboard shortcuts

- lib/components/SelectedView.jsx
- lib/containers/DeviceDetails.jsx
- lib/containers/ServerSetup.jsx
- package.json
- resources/css/styles.scss
This PR solves the issue of inconsistency with rendering the selected view new electron version.
The calculation of the view's height in js code is not necessary, using a simple css rule works with both electron 2 and 5.
> Simplify selected view height

- lib/components/AuthKeyEditor.jsx
There was a mismatch in arguments of `AuthKeyEditor.createPasskeyDisplayControls` between call site and definition.
> Fix keypress notification display

- lib/utils/api.js
This fixes [NCP-2734](https://projecttools.nordicsemi.no/jira/browse/NCP-2734) and [NCP-2735](https://projecttools.nordicsemi.no/jira/browse/NCP-2735): Neither the pairing dialog nor the device in the server setup showed up
anymore.
This was caused by a breaking change in immutable. With this code:
const MyRecord = Record({k: null})
const t1 = MyRecord({})
const t2 = MyRecord({k: undefined})
In immutable 3 in object `t1` the property `k` contained `null` (the
default value) while in `t2` it contained `undefined`. Thus in
immutable 3 default values were only used if a property was not
specified at all.
This changed in immutable 4: Here both `t1` and `t2` will contain `null`
for the property `k`. Thus default values are used if a property is not
specified at all or if it containes …
> Fix broken pairing and server setup

- lib/reducers/securityReducer.js
Fixes [NCP-2734](https://projecttools.nordicsemi.no/jira/browse/NCP-2734).
When trying to complete a pairing an error message was instead shown:
> Error when calling 'reduceApp': Cannot update within non-data-structure
> value in path ["connectionsSecParameters"]: [object Map]
This was caused by a combination of an old bug in the code and a change
in immutable-js 4:
In the old code an import for the Map of immutable was missing, which
meant in lib/reducers/securityReducer.js the Map of JavaScript was used
instead.
immutable-js 3 did work with the JavaScript variant of Map, but in a
questionable way, because it really mutated it, which means also other,
supposedly unmutable objects were mutated. immutable-js 4 now rejects
such mutation attempts as an error.
> Pairing was unpossible

- lib/reducers/__tests__/serverSetupReducer-test.js
- package.json
The newer release 4.0.0-rc12 (coming in through a transitive dependency
from pc-nrfconnect-devdep) brings in several bugs and we are uncertain
whether there are more. So we try a downgrade to the stable version to
see whether that works better.
> Downgrade immutable

- lib/components/DiscoveredDevice.jsx
Before 
> ![Scan result - broken](https://user-images.githubusercontent.com/260705/68764542-33227000-061b-11ea-968c-dac2ef97d744.png)
Now:
> ![Scan result](https://user-images.githubusercontent.com/260705/68764561-387fba80-061b-11ea-8825-6775eb07c652.png)
> Scan results wrongly showed advertisement keys

- lib/actions/adapterActions.js
Part of [NCP-2996](https://projecttools.nordicsemi.no/jira/browse/NCP-2996).
This enables the app to run with either serialport 7 (which had comName as a property) or serialport 8 (which moved to the property path and warns when still using comName).
> Harden against new serialport

- lib/actions/serverSetupActions.js
- lib/containers/ServerSetup.jsx
- lib/reducers/serverSetupReducer.js
When modifying server setup, if the user makes a change to a service, characteristic or descriptor, but then clicks on another of these components before clicking save, they will be presented with a discard dialog.
However this dialog currently does not do anything, and the changes are discarded regardless of the user clicking Yes or No. So for now we can just remove this dialog until we decide that we want to fix this behavior properly.
> Remove the server setup discard dialog

- lib/components/CentralDevice.jsx
Task NCP-3421
This will indicate to user if there are stored any bond keys. 
The "Delete bond information" in the menu is disabled if we have no bounds
> Improve UX for delete bond information

- lib/common/Persistentstore.js
- lib/containers/AdvertisingParams.jsx
- lib/containers/DiscoveredDevices.jsx
- lib/reducers/advertisingReducer.js
- lib/reducers/discoveryReducer.js
- resources/css/styles.scss
This pull request will persist user settings in "Discovered device" and "Advertising parameters". (https://projecttools.nordicsemi.no/jira/browse/NCP-3466)
Will also fix bug where advertising setup was not remembered when changing or reloading device without reloading app first.
> Feature/presist adv+scan params

- package.json
We moved the dependency to facilitate for the build pipeline, but this breaks the app, so revert changes.
> Revert moving electron store dependency

- Changelog.md
- lib/components/DescriptorItem.jsx
- package.json
TEXT format was being parsed correctly for characteristics, but not for descriptors.
(Contrieved) example after fix:
NCP-3758
> Add missing parsing of TEXT format for descriptors

- index.jsx
- lib/actions/adapterActions.js
- lib/actions/advertisingActions.js
- lib/actions/bleEventActions.js
- lib/actions/serverSetupActions.js
- lib/common/treeViewKeyNavigation.js
- lib/components/CentralDevice.jsx
- lib/components/ConfirmationDialog.jsx
- lib/components/ConnectionParamsControl.jsx
- lib/components/ConnectionUpdateRequestEditor.jsx
- lib/components/DfuEditor.jsx
- lib/components/DiscoveredDevice.jsx
- lib/components/EditableField.jsx
- lib/components/SidePanel.jsx
- lib/components/Spinner.jsx
- lib/containers/AdvertisingParams.jsx
- lib/containers/ConnectionParams.jsx
- lib/containers/DeviceDetails.jsx
- lib/containers/DeviceSelector.js
- lib/containers/SecurityParamsDialog.jsx
- lib/containers/ServerSetup.jsx
- lib/reducers/__tests__/discoveryReducer-test.js
- lib/reducers/__tests__/serverSetupReducer-test.js
- lib/reducers/deviceDetailsReducer.js
- lib/utils/bluetoothUuidApi.js
- lib/utils/uuid_definitions.js
- package-lock.json
- package.json
- resources/css/styles.scss
Part of https://trello.com/c/j6lBuPvA/112-check-and-update-all-apps-with-new-architecture-and-apply-new-device-selector-in-all-apps.
Converts this app to the new app architecture.
Two issues are remaining. Both will be fixed with a new version of `shared` next:
- The console shows a false error: <code>Warning: Failed prop type: Invalid prop `deviceSetup` key `allowCustomDevice` supplied to `DeviceSelector`.</code>
- The app currently does not work correctly with devices that are unknown but already have the correct firmware on them.
> Convert to new arch

- lib/components/ActionButton.jsx
- lib/components/AdvertisingData.jsx
- lib/components/AdvertisingListEntry.jsx
- lib/components/DfuEditor.jsx
- lib/components/PairingEditor.jsx
- lib/components/SecurityParamsControls.jsx
- lib/components/UuidLookup.jsx
- lib/components/__tests__/__snapshots__/DfuEditor-snapshot-test.jsx.snap
- lib/containers/AdvertisingParams.jsx
- lib/containers/AdvertisingSetup.jsx
- lib/containers/ConnectionParams.jsx
- lib/containers/SecurityParamsDialog.jsx
Part of https://trello.com/c/j6lBuPvA/112-check-and-update-all-apps-with-new-architecture-and-apply-new-device-selector-in-all-apps.
On a white background “outline-secondary” buttons are invisible unless one hovers over them. So switch to normal “secondary” buttons.
> Fix invisible buttons

- Changelog.md
- package-lock.json
- package.json
- src/config.ts
Version need to match with the standalone-ble application, and the JLink message (changed in the standalone application) need to match the rest of the apps.
> Synchronize version and JLink message

- src/config.ts
Reverts NordicSemiconductor/pc-nrfconnect-ble#267
It is not suppose to include `v`, because it uses the number in the filename inside
`downloadInstaller.ts`, which does not include `v`. As seen in `baseDownloadUrl`
the `v` is included in path.
> Revert "Add v to v4.0.4"

- package.json
The caret was wrong because we expect the app to continue to work with also future major versions like `4.0.0`.
> Correct engine specification

- .github/workflows/zoomin-publish-dev.yml
- .github/workflows/zoomin-publish.yml
- README.md
- doc/docs/dfu.md
- doc/docs/revision_history.md
Replaced Infocenter links with TechDocs.
----
Links to Infocenter that haven't been fixed (TBD): *links removed after checking with Ray*
----
Changelog not needed: doc file edits only.
> doc: update infocenter links
