lib/components/AttributeItem.jsx, lib/components/__tests__/__snapshots__/ServiceItem-snapshot-test.jsx.snap
Tested expanding Services, Characteristics and Descriptors on Connection Map
Tested expanding Services, Characteristics and Descriptors on Server Setup
Works properly and will not affect other functions in these two cases.
=> Easy expand

lib/actions/adapterActions.js
Enable serialport v6 on MacOS
Test on Windows
Test on Linux
Test on MacOS
=> Fix upgrading serialport

package.json
=> Bump up version number to v2.2.0

lib/components/__tests__/__snapshots__/ConnectedDevice-snapshot-test.jsx.snap, lib/components/__tests__/__snapshots__/DfuEditor-snapshot-test.jsx.snap, package.json
Recent build failed due to updated test environment dependencies.
=> Update snapshots and dependency fixing localstorage mock

lib/components/CountdownTimer.jsx, package.json
This PR is due to fixing proptype number issue.
=> Fix proptype number

lib/components/AdvertisingData.jsx, lib/components/UuidLookup.jsx, lib/components/input/UuidInput.jsx
Moved separated component into the compound input component for correct rendering.
=> Fix UUID lookup input addon component

index.jsx
This PR is related to https://github.com/NordicSemiconductor/pc-nrfconnect-core#318
=> Add releaseCurrentDevice configuration to ensure safe reopening

lib/actions/adapterActions.js, lib/actions/errorDialogActions.js, lib/components/AddNewItem.jsx, lib/components/AttributeItem.jsx, lib/components/DfuThroughputGraph.jsx, lib/components/LineChart.jsx, lib/containers/ServerSetup.jsx, package.json
In this PR simple logging handlers are added to upcoming SoftDevice v5 events.
Additionally obsolete react lifecycle events are updated and unmaintained charting library with simpler chart.js alternative.
=> Add handlers to SoftDevice v5 events

index.jsx, lib/actions/adapterActions.js
This PR is to allow user to use custom device.
=> Allow custom device

lib/containers/DfuDialog.jsx, lib/containers/ServerSetup.jsx, package.json
Electron dialog API was changed. Update accordingly.
https://github.com/electron/electron/blob/v8.2.5/docs/api/dialog.md
=> Updated code to reflect API changes in Electron

Changelog.md, lib/components/DfuEditor.jsx, lib/components/__tests__/__snapshots__/DfuEditor-snapshot-test.jsx.snap
=> Fix display of dfu package info

index.jsx, lib/actions/adapterActions.js, lib/components/SidePanel.jsx, package-lock.json, package.json
Fixes an error in 532d17d and uses one small enhancement of shared 5.2.0 in 1da6ab9.
=> Use shared 5.2.0

Changelog.md, package.json
Update changelog and bump the version
=> Mention new look & feel

src/index.tsx, src/style.css
Modified the spacing and outlay of the components in order to provide a better user experience in the proxy window. Focus on getting text and components consistent, in order for it not to look cluttered.
=> Clean up the design for install screen

Changelog.md, src/index.tsx
=> Modify text in accordance with tech writer review

src/config.ts, src/index.tsx, src/paths.ts
Change the path to be displayed more appropriately, adjust all file sizes to match latest build of the standalone application.
=> Minor adjustments for macOS

doc/docs/revision_history.md
Updated date for the latest doc update.
NCS-653.
=> doc: update revision history date

README.md, doc/docs/adding_uuid_defs.md, doc/docs/connecting_devices.md, doc/docs/index.md, doc/docs/installing.md, doc/docs/maintaining_server_setup.md, doc/docs/overview_and_ui.md, doc/docs/pairing_devices.md, doc/docs/revision_history.md, doc/docs/service_discovery.md, doc/docs/setting_up_application.md, doc/docs/troubleshooting.md, doc/docs/update_connection.md, doc/mkdocs.yml
- Commit 1: Housekeeping of mkdocs and changes to app name to match what is displayed in the launcher.
- Commit 2: Removal of nRF52840 USB problems section from troubleshooting. NCS-944.
=> doc: update troubleshooting and mkdocs

doc/docs/overview_and_ui.md, doc/docs/troubleshooting.md
Commit 1: Added a deprecation note about nRF CLT to the troubleshooting.md page.
NCSDK-30028.
Commit 2: Fixed a couple trivial build errors related to PNG/png.
=> doc: nrfjprog deprecation note

doc/docs/revision_history.md, doc/docs/troubleshooting.md
Added update for the previous doc commits.
NCSDK-30028.
=> doc: update revision history

doc/docs/revision_history.md, doc/docs/troubleshooting.md
Updated the note to mention archiving is done.
NCSDK-30153.
=> doc: update note about the nRF Command Line Tools
